default_language_version:
    python: python3.7
repos:
  - repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: debug-statements
      - id: check-merge-conflict
      - id: flake8
      - id: check-executables-have-shebangs
